version: '3'

services:
  spacex:
    container_name: spacex
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: spacex
      SLEEP_TIME: 5

networks:
  default:
    external:
      name: kafka-network
